### ISSUE TITLE
项目启动报错

### ISSUE THREAD

**Issue by ipengyo** [XGHeaven/cnode-angular-material#77]
`0 info it worked if it ends with ok
1 verbose cli [ '/Users/admin/Code/GitCode/nvm/versions/node/v4.3.1/bin/node',
1 verbose cli   '/Users/admin/Code/GitCode/nvm/versions/node/v4.3.1/bin/npm',
1 verbose cli   'start' ]
2 info using npm@2.14.12
3 info using node@v4.3.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart cnodejs-material@0.4.0
6 info start cnodejs-material@0.4.0
7 verbose unsafe-perm in lifecycle true
8 info cnodejs-material@0.4.0 Failed to exec start script
9 verbose stack Error: cnodejs-material@0.4.0 start:`gulp`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/Users/admin/Code/GitCode/nvm/versions/node/v4.3.1/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/Users/admin/Code/GitCode/nvm/versions/node/v4.3.1/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:821:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid cnodejs-material@0.4.0
11 verbose cwd /Users/admin/Code/Study/cnode-angular-material
12 error Darwin 15.4.0
13 error argv "/Users/admin/Code/GitCode/nvm/versions/node/v4.3.1/bin/node" "/Users/admin/Code/GitCode/nvm/versions/node/v4.3.1/bin/npm" "start"
14 error node v4.3.1
15 error npm  v2.14.12
16 error code ELIFECYCLE
17 error cnodejs-material@0.4.0 start:`gulp`
17 error Exit status 1
18 error Failed at the cnodejs-material@0.4.0 start script 'gulp'.
18 error This is most likely a problem with the cnodejs-material package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     gulp
18 error You can get their info via:
18 error     npm owner ls cnodejs-material
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
`

**Comment by XGHeaven** [comment]
现在已经修复，请尝试重新安装一次看看
